- src/CANDIDATE/ViewVouchers.js
Adding new features to ViewVouchers file.
> commiting viewvouchers

- src/CANDIDATE/UserProfile.js
updated new feature in candidate userprofile
> updating candidate userprofile

- src/ADMIN/Dashboard.jsx
Updated new filter in admin dashboard.
> Admindashboard1

- src/ADMIN/VoucherDashboard.jsx
Updated Assigned and Not Used Vouchers in Voucher dashboard.
> Updating voucher dashboard

- src/ADMIN/VoucherDashboard.jsx
updated download sample button in voucherdashboard
> updating downloadsample

- src/ADMIN/Dashboard.jsx
- src/ADMIN/VoucherDashboard.jsx
- src/CANDIDATE/Navbar.js
- src/CANDIDATE/UserProfile.js
- src/CANDIDATE/ViewVouchers.js
- src/CANDIDATE/requestVoucher.js
> updating changes

- src/ADMIN/Dashboard.css
- src/ADMIN/VoucherDashboard.jsx
Updating new changes in voucher dashboard.
> Updating changes in voucher dashboard

- src/CANDIDATE/ViewVouchers.js
> updating view vouchers c

- src/CANDIDATE/requestVoucher.js
update candidatename requestvoucher
> update candidatename requestvoucher

- src/ADMIN/VoucherRequests.jsx
- src/CANDIDATE/Navbar.js
- src/CANDIDATE/ProfileImageContext.jsx
- src/CANDIDATE/UserProfile.js
> updated frontend

- src/ADMIN/Dashboard.css
updated admin dashboard navbar styling
> updated admin dashboard navbar styling

- src/ADMIN/SignupForm.jsx
- src/CANDIDATE/Navbar.js
> signup update

- public/index.html
- src/ADMIN/Dashboard.css
- src/ADMIN/SignupForm.jsx
- src/ADMIN/VoucherDashboard.jsx
- src/ADMIN/VoucherRequests.jsx
- src/App.js
- src/CANDIDATE/Navbar.js
- src/CANDIDATE/ProfileImageContext.jsx
- src/CANDIDATE/UserProfile.js
- src/COMMON/Login.jsx
> fronend update

- package-lock.json
- package.json
- src/CANDIDATE/requestVoucher.js
> sana update

- src/ADMIN/Dashboard.css
- src/ADMIN/VoucherDashboard.jsx
- src/ADMIN/VoucherRequests.jsx
> View Score Image in dashboard

- src/ADMIN/Dashboard.css
- src/ADMIN/VoucherRequests.jsx
> adding deny request button

- src/ADMIN/Dashboard.css
- src/ADMIN/SignupForm.jsx
- src/ADMIN/VoucherDashboard.jsx
- src/ADMIN/VoucherRequests.jsx
- src/App.css
- src/COMMON/Login.jsx
> changes in dashboard styling

- src/ADMIN/Dashboard.css
- src/ADMIN/Dashboard.jsx
- src/ADMIN/Graph.css
- src/ADMIN/VoucherDashboard.jsx
- src/ADMIN/VoucherRequests.jsx
> changes in navbar styling

- src/ADMIN/Dashboard.css
- src/ADMIN/VoucherDashboard.jsx
- src/ADMIN/VoucherRequests.jsx
> changes in voucher requests

- src/ADMIN/CandidateList.jsx
- src/ADMIN/Dashboard.jsx
- src/ADMIN/VoucherRequests.jsx
- src/App.js
Adding eligibility in admin dashboard
> Adding eligibility in admin dashboard

- src/ADMIN/Dashboard.jsx
- src/ADMIN/Graph.css
- src/ADMIN/VoucherRequests.jsx
adding filters in graph dashboard
> adding filters in graph dashboard

- src/ADMIN/Dashboard.css
- src/ADMIN/VoucherRequests.jsx
styling update in voucher requests
> styling update in voucher requests
